
version: 2

models:
  - name: stg_drivers
    columns:
      - name: driver_id
        data_type: number
      - name: driver_ref
        data_type: varchar
      - name: number
        data_type: varchar
      - name: code
        data_type: varchar
      - name: forename
        data_type: varchar
      - name: surname
        data_type: varchar
      - name: dob
        data_type: date
      - name: nationality
        data_type: varchar
      - name: url
        data_type: varchar
