version: 2

sources:
  - name: dbt_jstayton
    database: raw  
    tables:
      - name: customer
      - name: orders
      - name: lineitem
  - name: tpch_sf100
    database: snowflake_sample_data
    tables:
      - name: nation
      - name: region